### ISSUE TITLE
arm64 architecture not supported

### ISSUE THREAD

**Issue by dfordequan** [tudelft/UnifiedOptitrackClients#23]
I tried both local build and docker with my arm64 machine (MacBook Apple silicon). Both build until around 80%, giving an error that NatNet SDK is only available for x86. I also checked the NatNet website and couldn't find an arm64 version. In the end, I switched to an x86 Linux machine and it works well with rox2px4 and log.

**Comment by tblaha** [comment]
Thanks for the report! Indeed, aarch64 is not supported by Optitrack. You may be able to run it via Rosetta, which I understand as some sort of virtualization of the x86 architecture on apple silicon. But we don't have plans to test or support this at the moment. We will make a not in the README though
